name = "JVMEval"
uuid = "8b5df349-bf38-4cca-a77f-77b65244730f"
authors = ["i"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
